import json
import re
from typing import Any, Dict, List

import pandas as pd
import requests
import snowflake.connector
import streamlit as st


# ============================================================
# Public Streamlit app for Snowflake Cortex Analyst
# ============================================================
# This app is for Streamlit Community Cloud / external hosting.
# It does NOT use _snowflake because _snowflake only works inside
# Streamlit in Snowflake.
#
# Required Streamlit secrets:
#
# [snowflake]
# account_url = "https://pka30578.east-us-2.azure.snowflakecomputing.com"
# account = "pka30578.east-us-2.azure"
# user = "CORTEX_PUBLIC_APP_USER"
# pat = "PASTE_YOUR_PAT_TOKEN_SECRET_HERE"
# role = "SALES_PUBLIC_APP_ROLE"
# warehouse = "COMPUTE_WH"
# database = "SALES_ANALYTICS_2025"
# schema = "RAW_DATA"
# semantic_model_file = "@SALES_ANALYTICS_2025.RAW_DATA.SEMANTIC_MODELS/sales_analytics_semantic_model.yaml"
# ============================================================


st.set_page_config(
    page_title="Snowflake AI Sales Data Insights",
    page_icon="❄️",
    layout="wide",
)


def cfg(name: str) -> str:
    """Read required config from Streamlit secrets."""
    try:
        value = st.secrets["snowflake"][name]
    except Exception:
        st.error(f"Missing Streamlit secret: [snowflake].{name}")
        st.stop()
    if value is None or str(value).strip() == "":
        st.error(f"Empty Streamlit secret: [snowflake].{name}")
        st.stop()
    return str(value).strip()


ACCOUNT_URL = cfg("account_url").rstrip("/")
ACCOUNT = cfg("account")
USER = cfg("user")
PAT = cfg("pat")
ROLE = cfg("role")
WAREHOUSE = cfg("warehouse")
DATABASE = cfg("database")
SCHEMA = cfg("schema")
SEMANTIC_MODEL_FILE = cfg("semantic_model_file")

API_ENDPOINT = f"{ACCOUNT_URL}/api/v2/cortex/analyst/message"


def call_cortex_analyst(prompt: str) -> Dict[str, Any]:
    """Call Snowflake Cortex Analyst REST API using a PAT token."""
    request_body = {
        "messages": [
            {
                "role": "user",
                "content": [{"type": "text", "text": prompt}],
            }
        ],
        "semantic_model_file": SEMANTIC_MODEL_FILE,
    }

    headers = {
        "Authorization": f"Bearer {PAT}",
        "X-Snowflake-Authorization-Token-Type": "PROGRAMMATIC_ACCESS_TOKEN",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    response = requests.post(
        API_ENDPOINT,
        headers=headers,
        data=json.dumps(request_body),
        timeout=60,
    )

    if response.status_code >= 400:
        raise RuntimeError(
            f"Cortex Analyst API failed: status={response.status_code}, body={response.text}"
        )

    return response.json()


def get_connection():
    """Create a Snowflake connector connection using PAT as password."""
    return snowflake.connector.connect(
        account=ACCOUNT,
        user=USER,
        password=PAT,
        role=ROLE,
        warehouse=WAREHOUSE,
        database=DATABASE,
        schema=SCHEMA,
    )


def is_safe_select(sql: str) -> bool:
    """Allow only read-only SQL generated by Cortex Analyst."""
    cleaned = sql.strip().lower()

    if not (cleaned.startswith("select") or cleaned.startswith("with")):
        return False

    # Block multiple statements and common DDL/DML/admin operations.
    blocked = [
        r";",
        r"\binsert\b",
        r"\bupdate\b",
        r"\bdelete\b",
        r"\bmerge\b",
        r"\bdrop\b",
        r"\btruncate\b",
        r"\balter\b",
        r"\bcreate\b",
        r"\bgrant\b",
        r"\brevoke\b",
        r"\bcopy\b",
        r"\bput\b",
        r"\bremove\b",
        r"\bcall\b",
    ]

    return not any(re.search(pattern, cleaned) for pattern in blocked)


def run_sql(sql: str) -> pd.DataFrame:
    """Run generated SQL and return a pandas dataframe."""
    if not is_safe_select(sql):
        raise ValueError("Blocked non-read-only SQL. Only SELECT/WITH queries are allowed.")

    conn = get_connection()
    try:
        cur = conn.cursor()
        try:
            cur.execute(sql)
            rows = cur.fetchall()
            columns = [desc[0] for desc in cur.description] if cur.description else []
            return pd.DataFrame(rows, columns=columns)
        finally:
            cur.close()
    finally:
        conn.close()


def render_response(response: Dict[str, Any]):
    """Render text, suggestions, generated SQL, tables, and simple charts."""
    content: List[Dict[str, Any]] = response.get("message", {}).get("content", [])

    for item in content:
        item_type = item.get("type")

        if item_type == "text":
            st.markdown(item.get("text", ""))

        elif item_type == "suggestions":
            suggestions = item.get("suggestions", [])
            if suggestions:
                with st.expander("Suggested follow-up questions", expanded=True):
                    for suggestion in suggestions:
                        if st.button(suggestion, key=f"suggestion_{suggestion}"):
                            st.session_state.pending_question = suggestion
                            st.rerun()

        elif item_type == "sql":
            sql = item.get("statement", "")
            with st.expander("Generated SQL", expanded=False):
                st.code(sql, language="sql")

            try:
                df = run_sql(sql)
                if df.empty:
                    st.info("Query returned no rows.")
                    continue

                st.dataframe(df, use_container_width=True)

                numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
                non_numeric_cols = df.select_dtypes(exclude=["number"]).columns.tolist()

                if len(df) > 1 and len(df) <= 30 and numeric_cols and non_numeric_cols:
                    chart_col = numeric_cols[0]
                    label_col = non_numeric_cols[0]
                    chart_df = df[[label_col, chart_col]].dropna()
                    st.bar_chart(chart_df.set_index(label_col)[chart_col])

            except Exception as exc:
                st.error(f"Error executing generated SQL: {exc}")


with st.sidebar:
    st.title("❄️ AI Data Insights")
    st.caption("Public Streamlit app connected to Snowflake Cortex Analyst")
    st.divider()

    st.markdown("**Quick Questions**")
    questions = [
        "What is the total revenue?",
        "Top 5 products by revenue",
        "Revenue by territory",
        "Compare Mountain vs Road bikes",
        "Daily sales trend",
        "Which model has the best margin?",
        "What is the 2023 budget?",
        "Average shipping days",
    ]

    for q in questions:
        if st.button(q, use_container_width=True):
            st.session_state.pending_question = q
            st.rerun()

    st.divider()
    st.caption("Built by Raj Manala")


st.title("❄️ Snowflake AI Sales Data Insights")
st.caption("Ask questions about your sales data in natural language.")

with st.expander("Connection status", expanded=False):
    st.write("Semantic model:")
    st.code(SEMANTIC_MODEL_FILE)
    st.write("Snowflake account URL:")
    st.code(ACCOUNT_URL)

if "messages" not in st.session_state:
    st.session_state.messages = []

pending = st.session_state.pop("pending_question", None)
user_input = pending or st.chat_input("Ask about your sales data...")

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            st.markdown(message["content"])
        else:
            render_response(message["content"])

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.chat_message("user"):
        st.markdown(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Asking Cortex Analyst..."):
            try:
                cortex_response = call_cortex_analyst(user_input)
                render_response(cortex_response)
                st.session_state.messages.append(
                    {"role": "assistant", "content": cortex_response}
                )
            except Exception as exc:
                st.error(str(exc))
