import json
import re
import time
from typing import Any, Dict, List

import pandas as pd
import requests
import streamlit as st


# ============================================================
# Public Streamlit app for Snowflake Cortex Analyst
# No snowflake-connector-python dependency.
# Uses:
#   1) Cortex Analyst REST API for natural-language-to-SQL
#   2) Snowflake SQL API REST endpoint to execute generated SQL
#
# Required Streamlit secrets:
#
# [snowflake]
# account_url = "https://pka30578.east-us-2.azure.snowflakecomputing.com"
# user = "CORTEX_PUBLIC_APP_USER"
# pat = "PASTE_YOUR_PAT_TOKEN_SECRET_HERE"
# role = "SALES_PUBLIC_APP_ROLE"
# warehouse = "COMPUTE_WH"
# database = "SALES_ANALYTICS_2025"
# schema = "RAW_DATA"
# semantic_model_file = "@SALES_ANALYTICS_2025.RAW_DATA.SEMANTIC_MODELS/sales_analytics_semantic_model.yaml"
# ============================================================


st.set_page_config(
    page_title="Snowflake AI Sales Data Insights",
    page_icon="❄️",
    layout="wide",
)


def cfg(name: str) -> str:
    """Read required config from Streamlit secrets."""
    try:
        value = st.secrets["snowflake"][name]
    except Exception:
        st.error(f"Missing Streamlit secret: [snowflake].{name}")
        st.stop()

    value = str(value).strip()
    if not value:
        st.error(f"Empty Streamlit secret: [snowflake].{name}")
        st.stop()
    return value


ACCOUNT_URL = cfg("account_url").rstrip("/")
USER = cfg("user")
PAT = cfg("pat")
ROLE = cfg("role")
WAREHOUSE = cfg("warehouse")
DATABASE = cfg("database")
SCHEMA = cfg("schema")
SEMANTIC_MODEL_FILE = cfg("semantic_model_file")

CORTEX_ANALYST_ENDPOINT = f"{ACCOUNT_URL}/api/v2/cortex/analyst/message"
SQL_API_ENDPOINT = f"{ACCOUNT_URL}/api/v2/statements"


def snowflake_headers() -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {PAT}",
        "X-Snowflake-Authorization-Token-Type": "PROGRAMMATIC_ACCESS_TOKEN",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def call_cortex_analyst(prompt: str) -> Dict[str, Any]:
    """Call Snowflake Cortex Analyst REST API using PAT authentication."""
    request_body = {
        "messages": [
            {
                "role": "user",
                "content": [{"type": "text", "text": prompt}],
            }
        ],
        "semantic_model_file": SEMANTIC_MODEL_FILE,
    }

    response = requests.post(
        CORTEX_ANALYST_ENDPOINT,
        headers=snowflake_headers(),
        data=json.dumps(request_body),
        timeout=60,
    )

    if response.status_code >= 400:
        raise RuntimeError(
            f"Cortex Analyst API failed: status={response.status_code}, body={response.text}"
        )

    return response.json()


def is_safe_select(sql: str) -> bool:
    """Allow only read-only SQL generated by Cortex Analyst."""
    cleaned = sql.strip().lower()

    if not (cleaned.startswith("select") or cleaned.startswith("with")):
        return False

    blocked_patterns = [
        r";",
        r"\binsert\b",
        r"\bupdate\b",
        r"\bdelete\b",
        r"\bmerge\b",
        r"\bdrop\b",
        r"\btruncate\b",
        r"\balter\b",
        r"\bcreate\b",
        r"\bgrant\b",
        r"\brevoke\b",
        r"\bcopy\b",
        r"\bput\b",
        r"\bremove\b",
        r"\bcall\b",
    ]

    return not any(re.search(pattern, cleaned) for pattern in blocked_patterns)


def submit_sql(sql: str) -> Dict[str, Any]:
    """Submit SQL to Snowflake SQL API."""
    body = {
        "statement": sql,
        "timeout": 60,
        "database": DATABASE,
        "schema": SCHEMA,
        "warehouse": WAREHOUSE,
        "role": ROLE,
    }

    response = requests.post(
        SQL_API_ENDPOINT,
        headers=snowflake_headers(),
        data=json.dumps(body),
        timeout=90,
    )

    if response.status_code >= 400:
        raise RuntimeError(
            f"Snowflake SQL API failed: status={response.status_code}, body={response.text}"
        )

    return response.json()


def poll_sql(statement_handle: str) -> Dict[str, Any]:
    """Poll a Snowflake SQL API statement until it returns results."""
    url = f"{SQL_API_ENDPOINT}/{statement_handle}"

    for _ in range(20):
        response = requests.get(
            url,
            headers=snowflake_headers(),
            timeout=60,
        )

        if response.status_code == 202:
            time.sleep(1)
            continue

        if response.status_code >= 400:
            raise RuntimeError(
                f"Snowflake SQL API polling failed: status={response.status_code}, body={response.text}"
            )

        return response.json()

    raise TimeoutError("SQL query is still running after waiting. Try a smaller question.")


def sql_result_to_dataframe(result: Dict[str, Any]) -> pd.DataFrame:
    """Convert Snowflake SQL API result JSON into a pandas dataframe."""
    meta = result.get("resultSetMetaData", {})
    row_type = meta.get("rowType", [])
    columns = [col.get("name", f"COL_{i+1}") for i, col in enumerate(row_type)]

    rows = result.get("data", [])

    if not columns:
        return pd.DataFrame(rows)

    df = pd.DataFrame(rows, columns=columns)

    # Basic type cleanup for charts/tables.
    for col_meta in row_type:
        name = col_meta.get("name")
        snowflake_type = str(col_meta.get("type", "")).upper()

        if name not in df.columns:
            continue

        if snowflake_type in {"FIXED", "REAL"} or "NUMBER" in snowflake_type:
            df[name] = pd.to_numeric(df[name], errors="ignore")
        elif "DATE" in snowflake_type or "TIMESTAMP" in snowflake_type:
            df[name] = pd.to_datetime(df[name], errors="ignore")

    return df


def run_sql(sql: str) -> pd.DataFrame:
    """Run generated SQL using Snowflake SQL API and return dataframe."""
    if not is_safe_select(sql):
        raise ValueError("Blocked non-read-only SQL. Only SELECT/WITH queries are allowed.")

    result = submit_sql(sql)

    # If Snowflake returns a handle without data, poll the result endpoint.
    statement_handle = result.get("statementHandle")
    if statement_handle and "data" not in result:
        result = poll_sql(statement_handle)

    return sql_result_to_dataframe(result)


def render_response(response: Dict[str, Any]) -> None:
    """Render Cortex Analyst text, suggestions, generated SQL, tables, and charts."""
    content: List[Dict[str, Any]] = response.get("message", {}).get("content", [])

    for item in content:
        item_type = item.get("type")

        if item_type == "text":
            st.markdown(item.get("text", ""))

        elif item_type == "suggestions":
            suggestions = item.get("suggestions", [])
            if suggestions:
                with st.expander("Suggested follow-up questions", expanded=True):
                    for suggestion in suggestions:
                        if st.button(suggestion, key=f"suggestion_{suggestion}"):
                            st.session_state.pending_question = suggestion
                            st.rerun()

        elif item_type == "sql":
            sql = item.get("statement", "")

            with st.expander("Generated SQL", expanded=False):
                st.code(sql, language="sql")

            try:
                df = run_sql(sql)

                if df.empty:
                    st.info("Query returned no rows.")
                    continue

                st.dataframe(df, use_container_width=True)

                numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
                non_numeric_cols = df.select_dtypes(exclude=["number"]).columns.tolist()

                if len(df) > 1 and len(df) <= 30 and numeric_cols and non_numeric_cols:
                    label_col = non_numeric_cols[0]
                    chart_col = numeric_cols[0]
                    chart_df = df[[label_col, chart_col]].dropna()
                    st.bar_chart(chart_df.set_index(label_col)[chart_col])

            except Exception as exc:
                st.error(f"Error executing generated SQL: {exc}")


with st.sidebar:
    st.title("❄️ AI Sales Insights")
    st.caption("Public app connected to Snowflake Cortex Analyst")
    st.divider()

    st.markdown("**Quick Questions**")

    quick_questions = [
        "What is the total revenue?",
        "Top 5 products by revenue",
        "Revenue by territory",
        "Compare Mountain vs Road bikes",
        "Daily sales trend",
        "Which model has the best margin?",
        "What is the 2023 budget?",
        "Average shipping days",
    ]

    for q in quick_questions:
        if st.button(q, use_container_width=True):
            st.session_state.pending_question = q
            st.rerun()

    st.divider()
    st.caption("Built by Raj Manala")


st.title("❄️ Snowflake AI Sales Data Insights")
st.caption("Ask questions about sales data in natural language. Powered by Cortex Analyst.")

with st.expander("Connection details", expanded=False):
    st.write("Semantic model:")
    st.code(SEMANTIC_MODEL_FILE)
    st.write("Snowflake account URL:")
    st.code(ACCOUNT_URL)

if "messages" not in st.session_state:
    st.session_state.messages = []

pending_question = st.session_state.pop("pending_question", None)
user_question = pending_question or st.chat_input("Ask about your sales data...")

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            st.markdown(message["content"])
        else:
            render_response(message["content"])

if user_question:
    st.session_state.messages.append({"role": "user", "content": user_question})

    with st.chat_message("user"):
        st.markdown(user_question)

    with st.chat_message("assistant"):
        with st.spinner("Asking Cortex Analyst..."):
            try:
                analyst_response = call_cortex_analyst(user_question)
                render_response(analyst_response)
                st.session_state.messages.append(
                    {"role": "assistant", "content": analyst_response}
                )
            except Exception as exc:
                st.error(str(exc))
