-- ============================================================
-- Public Streamlit Cortex Analyst App Setup
-- Run using ACCOUNTADMIN / USERADMIN as noted below.
-- Do not paste PAT token secrets into GitHub.
-- ============================================================

-- 1) Create limited app role
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SALES_PUBLIC_APP_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_ANALYST_USER
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT USAGE ON DATABASE SALES_ANALYTICS_2025
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT USAGE ON SCHEMA SALES_ANALYTICS_2025.RAW_DATA
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT USAGE ON SCHEMA SALES_ANALYTICS_2025.CURATED
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT READ ON STAGE SALES_ANALYTICS_2025.RAW_DATA.SEMANTIC_MODELS
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA SALES_ANALYTICS_2025.CURATED
TO ROLE SALES_PUBLIC_APP_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH
TO ROLE SALES_PUBLIC_APP_ROLE;

-- 2) Create service user
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS CORTEX_PUBLIC_APP_USER
  TYPE = SERVICE
  DEFAULT_ROLE = SALES_PUBLIC_APP_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = SALES_ANALYTICS_2025.RAW_DATA
  COMMENT = 'Service user for public Streamlit Cortex Analyst app';

GRANT ROLE SALES_PUBLIC_APP_ROLE TO USER CORTEX_PUBLIC_APP_USER;

-- 3) Create PAT authentication policy
USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS_2025.SECURITY;

CREATE OR REPLACE AUTHENTICATION POLICY PUBLIC_APP_PAT_POLICY
  AUTHENTICATION_METHODS = ('PROGRAMMATIC_ACCESS_TOKEN')
  PAT_POLICY = (
    DEFAULT_EXPIRY_IN_DAYS = 30
    MAX_EXPIRY_IN_DAYS = 90
    NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED
    REQUIRE_ROLE_RESTRICTION_FOR_SERVICE_USERS = TRUE
  );

ALTER USER CORTEX_PUBLIC_APP_USER
SET AUTHENTICATION POLICY PUBLIC_APP_PAT_POLICY;

-- 4) Generate the PAT token. Copy the token_secret immediately.
-- Snowflake shows token_secret only once.
ALTER USER CORTEX_PUBLIC_APP_USER
ADD PROGRAMMATIC ACCESS TOKEN PUBLIC_STREAMLIT_PAT
ROLE_RESTRICTION = 'SALES_PUBLIC_APP_ROLE'
DAYS_TO_EXPIRY = 30;
