-- Disable public app access after the demo
USE ROLE ACCOUNTADMIN;

ALTER USER CORTEX_PUBLIC_APP_USER
MODIFY PROGRAMMATIC ACCESS TOKEN PUBLIC_STREAMLIT_PAT
SET DISABLED = TRUE;

-- Or remove the token permanently:
-- ALTER USER CORTEX_PUBLIC_APP_USER
-- REMOVE PROGRAMMATIC ACCESS TOKEN PUBLIC_STREAMLIT_PAT;
